name: 'Create release'

inputs:
  token:
    description: "GitHub token"
    required: true
  nightly:
    description: "Boolean string ('true'/'false')"
    required: true
  artifact-id-release:
    description: "ID of the artifact that contains the release zip"
    required: true
  artifact-id-debug:
    description: "ID of the artifact that contains the debug zip"
    required: true

runs:
  using: composite
  steps:
    - name: Download build artifacts
      id: download-artifact
      uses: actions/download-artifact@v7
      with:
        artifact-ids: ${{ inputs.artifact-id-release }},${{ inputs.artifact-id-debug }}
        merge-multiple: true

    - name: Create ZIPs for release
      shell: pwsh
      run: |
        $downloadPath = "${{ steps.download-artifact.outputs.download-path }}"
        Get-ChildItem -Path $downloadPath -Directory | ForEach-Object {
          $dir = $_.FullName
          $zipName = "$dir.zip"
          7z a -tzip -mx=7 -mmt=on "$zipName" "$dir\*"
          Write-Host "Created $zipName"
        }

    - name: Calculate nightly release info
      if: ${{ inputs.nightly == 'true' }}
      id: nightly-info
      shell: pwsh
      run: |
        $shortHash = $env:GITHUB_SHA.Substring(0, 7)
        $date = Get-Date -Format 'dd.MM.yyyy HH:mm'
        "tag=nightly-$env:GITHUB_RUN_ID" >> $env:GITHUB_OUTPUT
        "name=Nightly - $shortHash ($date)" >> $env:GITHUB_OUTPUT

    - name: Create nightly release
      if: ${{ inputs.nightly == 'true' }}
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "${{ steps.download-artifact.outputs.download-path }}/*.zip"
        generateReleaseNotes: true
        name: ${{ steps.nightly-info.outputs.name }}
        prerelease: true
        removeArtifacts: true
        tag: ${{ steps.nightly-info.outputs.tag }}
        token: ${{ inputs.token }}

    - name: Create regular release
      if: ${{ inputs.nightly != 'true' }}
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "${{ steps.download-artifact.outputs.download-path }}/*.zip"
        generateReleaseNotes: true
        token: ${{ inputs.token }}
