if(NOT DEFINED GD3D11_SOURCE_DIR OR NOT DEFINED GD3D11_TARGET_DIR)
  message(FATAL_ERROR "GD3D11_SOURCE_DIR and GD3D11_TARGET_DIR are required")
endif()

file(MAKE_DIRECTORY "${GD3D11_TARGET_DIR}/GD3D11/shaders")

file(COPY "${GD3D11_SOURCE_DIR}/D3D11Engine/Shaders/" DESTINATION "${GD3D11_TARGET_DIR}/GD3D11/shaders")
file(COPY "${GD3D11_SOURCE_DIR}/blobs/data/" DESTINATION "${GD3D11_TARGET_DIR}/GD3D11/data")
file(COPY "${GD3D11_SOURCE_DIR}/blobs/Meshes/" DESTINATION "${GD3D11_TARGET_DIR}/GD3D11/Meshes")
file(COPY "${GD3D11_SOURCE_DIR}/blobs/Textures/" DESTINATION "${GD3D11_TARGET_DIR}/GD3D11/Textures")
file(COPY "${GD3D11_SOURCE_DIR}/blobs/Fonts/" DESTINATION "${GD3D11_TARGET_DIR}/GD3D11/Fonts")
file(COPY "${GD3D11_SOURCE_DIR}/blobs/libs/" DESTINATION "${GD3D11_TARGET_DIR}")
